---
collections:
  - name: containers.podman
    source: https://github.com/containers/ansible-podman-collections.git
    version: 1.19.0
    type: git

  - name: community.general
    source: https://github.com/ansible-collections/community.general.git
    version: 12.3.0
    type: git
